---
pipeline:
  publish_ansible:
    when:
      event: deployment
    image: plugins/docker
    repo: sonerdy/ansible
    tags: latest
    dockerfile: ansible.dockerfile
    secrets: [ docker_username, docker_password ]
